# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.2
          
      - name: Cache haxelib path
        uses: actions/cache@v2
        with:
          path: |
            %HAXELIB_ROOT%
          key: ${{ runner.os }}-android
          
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.2
        
      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: '11'
        
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e

      # Runs a set of commands using the runners shell
      - name: Lime Script
        run: |
          mkdir -p "%HAXELIB_ROOT%"
          haxelib setup "%HAXELIB_ROOT%"
          haxelib git lime https://github.com/Sirox228/lime --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib install flixel 4.11.0 --quiet
          haxelib run lime setup flixel --quiet
          haxelib install flxanimate 1.2.0 --quiet
          haxelib install hxp --quiet
          haxelib set lime git
          haxelib set openfl 9.1.0
          haxelib set flxanimate 1.2.0
          haxelib install hscript --quiet
          haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_ROOT
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib list
          
      - name: Build Log
        run: |
          haxelib run lime setup android
          haxelib run lime build android -release
          
      - uses: actions/upload-artifact@v2
        with:
          name: Android Build
          path: export/release/android/bin/app/build/outputs/apk/debug/
